### ISSUE TITLE
Hand Clears Skybox

### ISSUE THREAD

**Issue by ddutchie** [aestheticinteractive/Hover-VR-Interface-Kit#16] opened 2015-02-26 10:53 UTC
I've just imported USKy into my project, when I lift hovercast hand the skybox dissapears from view. Any idea why?

http://youtu.be/ySOhFfFyRNM

**Comment by zachkinstner** [comment] 2015-02-26 14:01
My first guess is that there is some kind of conflict between Hovercast's transparent shaders and the sky box. I can look into it more this afternoon. 

In the meantime, are you able to pack up a minimal Unity project that reproduces the issue? Maybe it would be as simple as a scene with just your sky box, Leap Motion hands, and Hovercast. That would allow me to jump right into debugging the issue.

**Comment by ddutchie** [comment] 2015-02-26 14:09
Unfortunately not. We have a power outage for the rest of the workday. 

Will have to send it tomorrow. 

Sorry. 
Gerard

**Comment by zachkinstner** [comment] 2015-02-26 17:28
I tried this with a standard Unity Skybox (the "Sunny1" material in the Standard Assets package) and could not reproduce it. Maybe there's something specific to uSky? Notes/thoughts:
- Does your code react to any of Hovercast's states, like "input available" or "menu is visible"? And if so, is there anything happening there that might affect uSky or its materials?
- There was a moment in the video where your hand appeared (jumbled up due to tracking) without the Hovercast menu, and the sky was still visible. Can you confirm that the sky goes black only when your palm is facing toward the camera, i.e. when Hovercast is visible?
- Try replacing usages of `Unlit/AlphaSelfIllum` in the Hovercast code with `Diffuse` instead. You can look for `Shader.Find("Unlit/AlphaSelfIllum")` in the code.

**Comment by ddutchie** [comment] 2015-02-26 21:08
It only happens when the left hand is in the view.  When it jumbled in the view it momentarily tracked as right hand.
So I am assuming it is hovercast. 

I will try swapping out shaders

Will test and package tomorrow. 

The previous demo just swapped out skyboxes, but this does not play well with unity5 realtime GI.
uSky offers a gradient based atmospheric scattered sky. With a 'time of day' input. The slider feeds its value into the time of day script. I can see the shadows change, so its definitely working, when i drop my hand the sky has also changed to the correct time of day.

But alas. Something is wrong.

**Comment by ddutchie** [comment] 2015-02-27 08:36
Very strange. I might have mentioned that I had some issues with the Leap Passthrough in a previous version of my project. The issues popped up again and I deleted all OVR and LEAP assets. Re Imported them and now it works. 

Passthrough and Realtime Skyupdate. 

[VR Interaction Test](http://youtu.be/Pkeds8-KybM)

**Comment by ddutchie** [comment] 2015-03-02 14:43
So the bug appeared today, but only on the left eye of the oculus. Chnaged a setting on one of my post effects and issue was on tight eye. Rearranged some post effects and changed render depth and issue was  
gone. 

Strange

**Comment by ddutchie** [comment] 2015-03-02 14:43
*changed *right

**Comment by zachkinstner** [comment] 2015-03-02 17:11
@ddutchie Thanks for the update, and I'm glad you found a fix!

I'm going to close this issue, but feel free to post additional details. If you were able to track this down to a specific setting, for example, that detail might help someone resolve a similar issue in the future.

**Closed as completed by zachkinstner** 2015-03-02 17:11 UTC
Labels: bug

**Comment by ddutchie** [comment] 2015-03-04 09:45
Issue is back. I have no idea what could be causing it. I have matched the settings from a project where it works. Still nothing.

**Comment by ddutchie** [comment] 2015-03-04 10:06
[Video of issue](http://youtu.be/Dr3IhOxoNJs)

**Comment by ddutchie** [comment] 2015-03-04 12:36
So Michael, the creator of uSky has given me a new shader which has solved the problem. 
Thanks. He should update his package in the future so no one has this issue.

**Comment by zachkinstner** [comment] 2015-03-04 12:40
Good to know, and thanks for the latest updates!
